### ISSUE TITLE
file name parsing doesn't use directory name

### ISSUE THREAD

**Issue by teuben** [dwkim78/ASTRiDE#4]
if I use
     Streak('abc/x1.fits')
it will dump the products in a local directory named 'x1', instead of the desired 'abc/x1', which I believe is an unexpected result.
Alternatively one can do
  Streak('abc/x1.fits',output_path='abc')
but I'm arguing the default behavior of output_path=None is unexpected.

**Comment by teuben** [comment]
correction:  the last example I gave overwrites and keeps the streaks in the directory...

**Comment by teuben** [comment]
Streak(ff,output_path=ff[:ff.rfind('.')])

is the desired default.

**Comment by dwkim78** [comment]
That is actually a desired result since the original comment for the output_path of Streak class is:
--------------------------
output_path: str, optional
        Path to save figures and output files. If None, the base filename
        is used as the folder name.
--------------------------

Nevertheless, I agree that your suggestion makes more sense than the original code. I'll implement this in the next release.

**Comment by teuben** [comment]
good idea. Imagine is somebody was using x1 also for the directory name, i.e.
x1/x1.fits, x1/x2.fits....   that might get confusing.
